### ISSUE TITLE
Reports wrong RAM amout

### ISSUE THREAD

**Issue by brentrjones9** [CherryPill/system_info#70] opened 2020-02-29 16:08 UTC
I have 32 GB RAM. The program says 16.  Windows sys info reports 32. 
I used SystemInfo_x86_1.4.1.exe

**Comment by smaragdus** [comment] 2020-03-01 02:31
I encountered the same issue- wrong RAM detection. My machine has 16 GB of RAM yet according to [SystemInfo](https://github.com/CherryPill/system_info) version [1.4.1](https://github.com/CherryPill/system_info/releases/tag/v.1.4.1) it has only 4 GB of RAM, screens:

**SystemInfo**

![SystemInfo 1 4 1 - 2020-03-01 - error - 002](https://user-images.githubusercontent.com/9025757/75618334-4713c280-5b75-11ea-8d69-854d5edb8a9e.png)

**HWiNFO**

![HWiNFO64 5 34 2930 - 2020-03-01 - 002](https://user-images.githubusercontent.com/9025757/75618340-5d218300-5b75-11ea-9be2-fa4f6ef9f65b.png)

I hope this wrong RAM detection will be fixed.

**Comment by DUDESEKP** [comment] 2020-03-01 15:15
Same here. reports 16 when i have 32

**Comment by CherryPill** [comment] 2020-03-02 08:54
The bug seems to affect all versions after 1.3, versions prior to and including 1.3 seem to be free of this bug. So it has to do with the recent changes of the internal mechanism of getting the hardware information. Will fix it when I get home.

**Comment by smaragdus** [comment] 2020-03-02 13:52
You are right, I have just checked version [1.3](https://github.com/CherryPill/system_info/releases/tag/v1.3) and it really shows the correct amount of RAM, screen:

![SystemInfo 1 3 0 - 2020-03-02 - 002](https://user-images.githubusercontent.com/9025757/75681619-9b659200-5c9c-11ea-90e6-07425908cf86.png)

As seen in  the screen this version also detects RAM type while later versions don't.

**Off-topic 1**

Until version 1.3 there were both x32 and x64 builds but since version 1.4 there are only x32 builds. WIll the x64 build be restored in future releases? Does the fact that I am using a x32 build on a x64 system have anything in common with the wrong RAM detection?

**Off-topic 2**

[SystemInfo](https://github.com/CherryPill/system_info) does not save any settings, right?

**Comment by CherryPill** [comment] 2020-03-02 15:02
> Does the fact that I am using a x32 build on a x64 system have anything in common with the wrong RAM detection?

No, it has nothing to do with that. WMI queries simply fetch the information from tables, I just somehow messed up when I was refactoring code. Honestly, there is really no point in having both x64 and x86 versions, since the application logic doesn't utilize libraries or has code that needs extended 64-bit registers or instructions sets, and it doesn't use memory over 4gb, also the RAM capacity in bytes is written into a 64-bit uint which is basically 2 32-bit ints on a x86 machine. Which is why the x86 1.3 version works on a 64bit machine and shows the correct value.



> [SystemInfo](https://github.com/CherryPill/system_info) does not save any settings, right?

Not at this point, no. What settings would you like to see?

**Comment by CherryPill** [comment] 2020-03-02 18:00
@smaragdus It is truly portable, the only times it accesses your storage is when it saves the exported data in html/txt or saves the screenshot on the system. It does silently save a temporary image when you upload your screenshot to gyazo, but then the temporary image is deleted. If you've ever uploaded a screenshot to gyazo with it, there should be SystemInfo directory in %appdata%, but most of the time it's empty, you can delete the directory if you want, but it will be recreated the next time you'll want to upload a screenshot.

**Comment by CherryPill** [comment] 2020-03-02 18:28
Should be fixed now. If it's not working for you, please reopen the issue. 

The issue had to do with me forgetting to loop through the enumerator to gather RAM from all slots, so it only gathered info for RAM present in one slot. The issue didn't surface when testing because I'm using only one RAM slot. 

https://github.com/CherryPill/system_info/releases/tag/v1.4.2

**Closed by CherryPill** 2020-03-02 18:28 UTC
Labels: bug, cause established

**Comment by smaragdus** [comment] 2020-03-02 23:01
@CherryPill 

First, thank you for the quick fix and for the detailed explanation- I have just tested SystemInfo version [1.4.2](https://github.com/CherryPill/system_info/releases/tag/v1.4.2) and I can confirm that now the program shows the true amount of RAM.

Second- thank you for confirming that SystemInfo is portable. As I don't use [Gyazo](https://gyazo.com/) (I use a similar service- [imgbox](https://imgbox.com/)) I am not affected of that folder created in AppData. If it happens that in the future you choose that the program would save some settings you may provide an option the configuration file to be saved in program folder.

If it happens that I encounter a problem with SystemInfo in the future I will report it.

Best regards
